// Content collection config for the "fr" (French grammar reference) collection.
// Schema mirrors .astro/collections/fr.schema.json (auto-generated by Astro).
import { defineCollection } from 'astro:content';
import { z } from 'astro/zod';

const fr = defineCollection({
  type: 'content',
  schema: z.object({
    title_uk: z.string(),
    title_fr: z.string(),
    description_uk: z.string(),
    category: z.string(),
    order: z.number().default(100),
    related: z.array(z.string()).default([]),
    tags: z.array(z.string()).default([]),
    formula: z.boolean().default(false),
    toc: z.boolean().default(true),
    featured: z.boolean().default(false),
  }),
});

export const collections = { fr };
